# Generated by Django 5.1.6 on 2025-02-06 22:19

import insuranceManager.api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('home', 'Home'), ('auto', 'Auto'), ('life', 'Life')], max_length=20)),
                ('expiry_date', models.DateTimeField(validators=[insuranceManager.api.models.validate_past_date])),
            ],
            options={
                'verbose_name_plural': 'Policies',
            },
        ),
    ]
